In [1]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Embedding 
import numpy as np

In [3]:
embedding_layer = Embedding(input_dim=10,output_dim=4,input_length=2)
model = Sequential()
model.add(embedding_layer)
model.compile('adam','mse')

In [4]:
input_data = np.array([[1,2]])
pred = model.predict(input_data)

In [9]:
input_data.shape

(1, 2)

In [8]:
pred

array([[[ 0.00083462, -0.01975002,  0.03450939, -0.01971873],
        [ 0.02259985, -0.02334529, -0.04228443,  0.0347853 ]]],
      dtype=float32)

In [10]:
embedding_layer.weights

[<tf.Variable 'embedding_1/embeddings:0' shape=(10, 4) dtype=float32, numpy=
 array([[ 0.04084532, -0.0031028 , -0.01624794, -0.01226185],
        [ 0.00083462, -0.01975002,  0.03450939, -0.01971873],
        [ 0.02259985, -0.02334529, -0.04228443,  0.0347853 ],
        [ 0.04236564, -0.02644359,  0.04673142,  0.02822736],
        [-0.0157032 , -0.0050971 , -0.04665619,  0.03820372],
        [-0.00836394,  0.00891324, -0.01956218, -0.04239134],
        [ 0.02069208,  0.0154883 ,  0.02953542, -0.04117895],
        [ 0.04298091, -0.0456371 ,  0.00476369, -0.03849069],
        [ 0.04002675,  0.03703339,  0.02240428, -0.00590714],
        [ 0.00797691,  0.0108548 , -0.03476025,  0.00874332]],
       dtype=float32)>]

In [12]:
from numpy import array 
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences 
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Flatten, Embedding,Dense

In [26]:
#Define 10 restaurant reviews 
reviews =[
          'Never coming back!',
          'horrible service',
          'rude waitress',
          'cold food',
          'horrible food!',
          'awesome',
          'awesome services!',
          'rocks',
          'poor work',
          'couldn\'t have done better'
]
labels = array([1,1,1,1,1,0,0,0,1,0])

In [27]:
vocab_size = 50
encoded_reviews = [one_hot(d,vocab_size) for d in reviews]
print(f'encoded reviews : {encoded_reviews}')

encoded reviews : [[15, 3, 7], [37, 22], [47, 43], [10, 8], [37, 8], [16], [16, 22], [16], [39, 10], [17, 21, 25, 12]]


In [28]:
max_length = 4
padded_reviews =pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
print(padded_reviews)

[[15  3  7  0]
 [37 22  0  0]
 [47 43  0  0]
 [10  8  0  0]
 [37  8  0  0]
 [16  0  0  0]
 [16 22  0  0]
 [16  0  0  0]
 [39 10  0  0]
 [17 21 25 12]]


In [29]:
model = Sequential()
embedding_layer = Embedding(input_dim=vocab_size,output_dim=8,input_length=max_length)
model.add(embedding_layer)
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['acc'])

In [30]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 4, 8)              400       
                                                                 
 flatten_1 (Flatten)         (None, 32)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________


In [31]:
model.fit(padded_reviews,labels,epochs=100,verbose=2)

Epoch 1/100
1/1 - 1s - loss: 0.7017 - acc: 0.3000 - 1s/epoch - 1s/step
Epoch 2/100
1/1 - 0s - loss: 0.6995 - acc: 0.3000 - 11ms/epoch - 11ms/step
Epoch 3/100
1/1 - 0s - loss: 0.6973 - acc: 0.3000 - 9ms/epoch - 9ms/step
Epoch 4/100
1/1 - 0s - loss: 0.6951 - acc: 0.4000 - 11ms/epoch - 11ms/step
Epoch 5/100
1/1 - 0s - loss: 0.6929 - acc: 0.6000 - 13ms/epoch - 13ms/step
Epoch 6/100
1/1 - 0s - loss: 0.6908 - acc: 0.7000 - 12ms/epoch - 12ms/step
Epoch 7/100
1/1 - 0s - loss: 0.6886 - acc: 0.7000 - 11ms/epoch - 11ms/step
Epoch 8/100
1/1 - 0s - loss: 0.6865 - acc: 0.8000 - 12ms/epoch - 12ms/step
Epoch 9/100
1/1 - 0s - loss: 0.6843 - acc: 0.8000 - 12ms/epoch - 12ms/step
Epoch 10/100
1/1 - 0s - loss: 0.6822 - acc: 0.8000 - 13ms/epoch - 13ms/step
Epoch 11/100
1/1 - 0s - loss: 0.6801 - acc: 0.9000 - 15ms/epoch - 15ms/step
Epoch 12/100
1/1 - 0s - loss: 0.6780 - acc: 1.0000 - 12ms/epoch - 12ms/step
Epoch 13/100
1/1 - 0s - loss: 0.6759 - acc: 1.0000 - 11ms/epoch - 11ms/step
Epoch 14/100
1/1 - 0s - los

In [38]:
embedding_layer.get_weights()[0].shape

(50, 8)

In [39]:
embedding_layer.get_weights()[0][0]

array([-0.09047195, -0.11975341, -0.01995972, -0.03484193, -0.11184743,
        0.02331798, -0.02123079, -0.04693019], dtype=float32)